# Generated by Django 4.1.7 on 2023-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('type_of_company', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Not IT'), ('Mobile Phones', 'Mobile Phones')], max_length=100)),
                ('established_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
