# Generated by Django 4.1.7 on 2023-04-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_id',
            new_name='company',
        ),
    ]
